import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HeroHeader from './components/HeroHeader'
import NavButtons from './components/NavButtons'
import {data} from '../data/data'
import { useEffect, useState } from 'react'
import Posts from './components/Posts'
import Contacts from './components/Contacts'

const Home: NextPage = () => {
  const [apiData, setApiData] = useState(data)

  const [index, setIndex] = useState(0)
  useEffect(() => {
    setApiData(data)
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HeroHeader/>
        <Contacts/>
        <NavButtons apiData={apiData} handleIndexState={setIndex} index={index}/>
        <Posts index={index} apiData={apiData}/>
    
      </main>
    </div>
  )
}
export const getStaticProps = (context: string) => {
  console.log('env mensage', process.env.UNSPLASH_API_KEY)
  return {
    props:{ }
}

}

export default Home